Script started on 2020-09-26 15:57:26-06:00 [TERM="xterm" TTY="/dev/pty0" COLUMNS="134" LINES="71"]
]0;~/CPSC355/abojohnAssignment1
[32mabojo@ROYPC [33m~/CPSC355/abojohnAssignment1[0m
$ assign[K[K[K[K[K[K,[K./assign1.o [K
Please enter valid arguments

	Farewell
]0;~/CPSC355/abojohnAssignment1
[32mabojo@ROYPC [33m~/CPSC355/abojohnAssignment1[0m
$ ./assign1.o 1 1
Please enter a valid size

	Farewell
]0;~/CPSC355/abojohnAssignment1
[32mabojo@ROYPC [33m~/CPSC355/abojohnAssignment1[0m
$ ./assign1.o 1 1[K[K[K5 5

	Creating random table... 

Displaying table:
0 4 3 0 8 
8 9 3 4 8 
6 1 0 8 5 
1 9 2 3 8 
4 8 3 7 6 

Enter the index of the word you are searching for: 2
How many top documents you want to retrieve? (Enter 0 to exit): 0 4

	Searching...

	Sorting...

results (From lowest to highest freqency):

Result #1: 0

Result #2: 4

Result #3: 1

Result #4: 3

	Logging to file...

Displaying table:
0 4 3 0 8 
8 9 3 4 8 
6 1 0 8 5 
1 9 2 3 8 
4 8 3 7 6 

Enter the index of the word you are searching for: 1
How many top documents you want to retrieve? (Enter 0 to exit): 3

	Searching...

	Sorting...

results (From lowest to highest freqency):

Result #1: 3

Result #2: 4

Result #3: 1

	Logging to file...

Displaying table:
0 4 3 0 8 
8 9 3 4 8 
6 1 0 8 5 
1 9 2 3 8 
4 8 3 7 6 

Enter the index of the word you are searching for: 1
How many top documents you want to retrieve? (Enter 0 to exit): 0

	Farewell
]0;~/CPSC355/abojohnAssignment1
[32mabojo@ROYPC [33m~/CPSC355/abojohnAssignment1[0m
$ ./assign1.o 5 5 occur[K[K[K[K[Ka[Kdoes[K[K[K[Knonexistance[K[Kntfie[Kle.txt

	Initializing form file... 

Unable to open the file: nonexistanntfile.txt

	Farewell
]0;~/CPSC355/abojohnAssignment1
[32mabojo@ROYPC [33m~/CPSC355/abojohnAssignment1[0m
$ ./assign1.o 5 5 nonexistanntfile.txt[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Koccuranc[K[K[Kences2.txt

	Initializing form file... 

Displaying table:
1 2 3 4 5 
5 4 3 2 1 
1 5 1 7 2 
2 4 2 7 8 
7 2 6 2 6 

Enter the index of the word you are searching for: 1
How many top documents you want to retrieve? (Enter 0 to exit): 5

	Searching...

	Sorting...

results (From lowest to highest freqency):

Result #1: 2

Result #2: 1

Result #3: 3

Result #4: 0

Result #5: 4

	Logging to file...

Displaying table:
1 2 3 4 5 
5 4 3 2 1 
1 5 1 7 2 
2 4 2 7 8 
7 2 6 2 6 

Enter the index of the word you are searching for: 1
How many top documents you want to retrieve? (Enter 0 to exit): 0

	Farewell
]0;~/CPSC355/abojohnAssignment1
[32mabojo@ROYPC [33m~/CPSC355/abojohnAssignment1[0m
$ exit
exit

Script done on 2020-09-26 15:59:47-06:00 [COMMAND_EXIT_CODE="1"]
