Script started on 2021-01-30 01:53:39-07:00
]0;john.abo@csx:~/cpsc359/asgm/1/gamejohn.abo@csx:~/cpsc359/asgm/1/game$ gcc game.c -pthread -o game
]0;john.abo@csx:~/cpsc359/asgm/1/gamejohn.abo@csx:~/cpsc359/asgm/1/game$ ./game
main thread running
 -  -  - 
 -  -  - 
 -  -  - 
main thread running
 -  -  - 
 -  -  - 
 X  O  - 
main thread running
 -  X  - 
 O  -  - 
 X  O  - 
main thread running
 X  X  - 
 O  O  - 
 X  O  - 
main thread running
 X  X  - 
 O  O  O 
 X  O  X 
O wins 
]0;john.abo@csx:~/cpsc359/asgm/1/gamejohn.abo@csx:~/cpsc359/asgm/1/game$ ./game
main thread running
 -  -  - 
 -  -  - 
 -  -  - 
main thread running
 -  -  - 
 -  -  O 
 -  -  X 
main thread running
 -  -  - 
 -  -  O 
 O  X  X 
main thread running
 -  -  - 
 O  X  O 
 O  X  X 
main thread running
 -  X  - 
 O  X  O 
 O  X  X 
X wins 
]0;john.abo@csx:~/cpsc359/asgm/1/gamejohn.abo@csx:~/cpsc359/asgm/1/game$ ./game
main thread running
 -  -  - 
 -  -  - 
 -  -  - 
main thread running
 -  X  O 
 -  -  - 
 -  -  - 
main thread running
 -  X  O 
 X  O  - 
 -  -  - 
main thread running
 O  X  O 
 X  O  - 
 X  -  - 
main thread running
 O  X  O 
 X  O  - 
 X  X  O 
main thread running
 O  X  O 
 X  O  X 
 X  X  O 
draw
]0;john.abo@csx:~/cpsc359/asgm/1/gamejohn.abo@csx:~/cpsc359/asgm/1/game$ ./game
main thread running
 -  -  - 
 -  -  - 
 -  -  - 
main thread running
 -  -  O 
 -  -  - 
 -  X  - 
main thread running
 X  -  O 
 O  -  - 
 -  X  - 
main thread running
 X  X  O 
 O  O  - 
 -  X  - 
main thread running
 X  X  O 
 O  O  X 
 O  X  - 
O wins 
]0;john.abo@csx:~/cpsc359/asgm/1/gamejohn.abo@csx:~/cpsc359/asgm/1/game$ exit
exit

Script done on 2021-01-30 01:54:15-07:00
